version: "3"

services:
  web:
    image: nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - $NGINX_PORT:80
    volumes:
      - "./drupal/web:/var/www/html"
      - "./drupal/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./drupal/php:/usr/local/etc/php"
    depends_on:
      - php    

  php:
    image: drupal:$DRUPAL_TAG
    container_name: "${PROJECT_NAME}_drupal"
    volumes:
      - "./drupal/web:/var/www/html"
      - "./drupal/php:/usr/local/etc/php"
    restart: always
    depends_on:
      - mysql    

  mysql:
    image: mysql:$MYSQL_TAG
    container_name: "${PROJECT_NAME}_mysql"
    ports:
      - 3360:3306
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - "./drupal/mysql:/var/lib/mysql"
    restart: always

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025